apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-dev
  namespace: charles-experiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-dev
  template:
    metadata:
      labels:
        app: python-dev
    spec:
      containers:
      - name: python-dev
        image: python:3.9
        command: ["/bin/sh", "-c", "while true; do sleep 30; done"]
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: code
          mountPath: /app
      volumes:
      - name: code
        emptyDir: {}
